### ISSUE TITLE
too generic names in tf_api.pas

### ISSUE THREAD

**Issue by Alexey-T** [zsoltszakaly/tensorflowforpascal#3]
```

type
  OpaqueType = record
    end;
  charPtr = PAnsiChar;
  charPtrPtr = ^charPtr;
  charPtrPtrPtr = ^charPtrPtr;
  cint64Ptr = ^cint64;
  cint64PtrPtr = ^cint64Ptr;
  csize_tPtr = ^csize_t;
  pointerPtr = ^Pointer;
  cfloatPtr = ^cfloat;
  cintPtr = ^cint;
  cintPtrPtr = ^cintPtr;
```

**Comment by zsoltszakaly** [comment]
As mentioned in the Header of my tf_api.pas
`Credit: This unit is based on the c_api.inc created by Phil Hess, based on the C header file c_api.h of TensorFlow`
I simply inherited the names from c_api.inc and that is based on c_api.h, and I did not bother trying to rename the types used there.
