### ISSUE TITLE
make a class here?

### ISSUE THREAD

**Issue by Alexey-T** [zsoltszakaly/tensorflowforpascal#4]
```
type
  TF_Code = clong;
  TF_Status = OpaqueType;
  TF_StatusPtr = ^TF_Status;
function TF_NewStatus: TF_StatusPtr; cdecl; external;
procedure TF_DeleteStatus(param1: TF_StatusPtr); cdecl; external;
procedure TF_SetStatus(s: TF_StatusPtr; code: TF_Code; msg: charPtr); cdecl; external;
function TF_GetCode(s: TF_StatusPtr): TF_Code; cdecl; external;
function TF_Message(s: TF_StatusPtr): charPtr; cdecl; external;
function TF_CheckStatus(AStatusPtr:TF_StatusPtr):Boolean;

type
  TF_Buffer = record
    data: pointer;
    length: csize_t;
    data_deallocator: procedure (data: pointer; length: csize_t); cdecl;
    end;
  TF_BufferPtr = ^TF_Buffer;
function TF_NewBufferFromString(proto: pointer; proto_len: csize_t): TF_BufferPtr; cdecl; external;
function TF_NewBuffer: TF_BufferPtr; cdecl; external;
procedure TF_DeleteBuffer(param1: TF_BufferPtr); cdecl; external;
function TF_GetBuffer(buffer: TF_BufferPtr): TF_Buffer; cdecl; external;
```

Maybe move all these into a class? with "class function".

**Comment by zsoltszakaly** [comment]
I do not understand the suggestion!
These are external functions. As far as I know there is no mechanism to link a Pascal object's (or class's) method directly to an external C function (how nice it would be to link a Pascal object to a C++ class like that). The only way would be to use it first as a wrapper (what can be a class with class functions as suggested) and inside the wrapper call the external functions just like here. This would only add complications, with no benefit.
Do I miss something?
P.S. And as said for another comment, I do not see a benefit of a static object with class functions only vs. using a unit like that.

**Comment by Alexey-T** [comment]
external functions. sorry, indeed they must be separate!
