### ISSUE TITLE
TF_StringDecode undefined symbol

### ISSUE THREAD

**Issue by fredconex** [zsoltszakaly/tensorflowforpascal#5]
I'm trying to use your library with Lazarus, I've downloaded the tensorflow.dll (latest version), but I'm gettting those errors below

project1.lpr(24,1) Error: Undefined symbol: TF_StringEncodedSize
project1.lpr(24,1) Error: Undefined symbol: TF_StringEncode

Any idea how to fix those? from what I've read those functions aren't part of newer versions of tensorflow but I couldn't find an older release for test, yet removing those functions also lead to more errors.

Btw, Thanks for the contribution

**Comment by zsoltszakaly** [comment]
I am using Linux, so I have no experience with .dll.
I tried to recompile my examples and they work.
I tried to look for TF_StringEncode and TF_StringEncodedSize, but I do not have them in any of the sources. I found it in an old c_api.h but - as you also say, - it is something deprecated: https://www.exxactcorp.com/blog/News/tensorflow-2-4-0-released. I still have 1.15, (I did not use TF for a while, but will upgrade it now) but I do not have this problem.
If you show your code that generates the error, I will try to look into it.

**Comment by zsoltszakaly** [comment]
I upgraded to 2.11 and now I see the problem. Will work on it and come back when solved.
Thanks for pointing out.

**Comment by zsoltszakaly** [comment]
I uploaded a new tf_api_temp.pas. Try that (renamed to tf_api.pas). Then tf_tensors.pas will not compile in CreateTensorString (2 identical named routines). The body of them need to be commented. The rest should work.
Still working on the fixing of the String part as well (but I do not yet understand the structure of a String type tensor).
Will come back, when that is fixed as well.
Please let me know your experiences.

**Comment by fredconex** [comment]
Thanks, that actually helped, I also had to comment out lines that still use the TF_StringEncode/Size from tf_tensor, I'm still learning it too but I believe that I may not need to use those functions? my plan is to create a neural network using it

**Comment by zsoltszakaly** [comment]
Yes, that is what I wrote as well. You need to comment out the body (best not only few lines) of the two CreateTensorString routines in tf_tensors.pas. Hence you cannot use anything where a string type tensor is used. I am still trying to make that work too.
For a numeric only NN you do not need that, so you can use it. You can check the mnist program I also uploaded. That is doing the same thing, maybe a good point to start from.

**Comment by zsoltszakaly** [comment]
It seems that a number of Operators also changed, deprecated or the parameter list changed. To use them, the tf_wrapper has to be re-run, but then again the ops.pbtxt is also changed (added summary and description). So, the wrappermaker also needs update. Working on them, soon will be available.

**Comment by zsoltszakaly** [comment]
I think it works. Other than the CreateTensorString should work, but even CreateTensorString for single string is OK. The rest is being worked on.
Also the examples are being re-done (some operations disappeared between the releases, so cannot be used). It will take some more time.
I will close this issue now. If you find something else, please reopen or open a new one.

**Comment by fredconex** [comment]
Thank you very much, I will let you know if I find something else.

**Comment by zsoltszakaly** [comment]
I completed the update. If you want to make a DNN then you might want to check the mnist.pas in the examples folder. That works (far from optimal, it is more a demo of what can be done). Would appreciate any feedback.
