### ISSUE TITLE
GNU GPL

### ISSUE THREAD

**Issue by Dingo64** [zsoltszakaly/tensorflowforpascal#7]
Any program using GNU GPL must have its full source code released as GNU GPL. So releasing this as GNU GPL basically means it can be only used in free, open source hobbyist projects.

**Comment by zsoltszakaly** [comment]
Oh, I am not really familiar with these :-(. I just copied it from another similar project.
Actually I am OK to use it wherever needed, other than selling my part for money. If you can recommend a better license, I can change it.
I will need to study a bit these legal stuff.

**Comment by Dingo64** [comment]
Usually people use for open source: MIT, Apache 2.0, BSD or LGPL.
All of these can be used in closed-source programs and all require programmers to state what library is used in their programs and who made it.

**Comment by zsoltszakaly** [comment]
I will study it, but if this is the only reason why you would not use it, just let me know and I give you permission.
